### ISSUE TITLE
Android, Opore v50, Impending Doom Ship

### ISSUE THREAD

**Issue by GeneralsDuty** [xamionex/Opore-Mod#5]
**Describe the bug**
So far I have been unable to get the Impending Doom ship to fire with touch controls, the targeting feature that normally appears when in range or by tapping on the enemy does not appear. Unrelated but for some reason the ships swaying idle animation is bit glitchy/jittery inside enemy drop point.

**Expected behaviour**
From what I've seen in the awp-ship.json file and screenshots the ship is suppose to shoot meltdown beams.

**Screenshots**
Expected behaviour: ![Preview14](https://user-images.githubusercontent.com/57879662/71172837-05c98180-22ad-11ea-8c2a-6be96397af55.png)

![Screenshot_20191219-215928671](https://user-images.githubusercontent.com/57879662/71172015-e893b380-22aa-11ea-90ac-52acf224b696.jpg)

[Video](https://youtu.be/4qmSSwm7BzA) 

**Smartphone (please complete the following information):**
 - Device: Asus ROG phone 2
 - OS: Android 9
 - Browser: NA
 - Version: [Android]BE-6350, BE-6320, v100.1

**Comment by xamionex** [comment]
I just found this out this morning, i don't know why it doesn't shoot but i know why its "jittery" in the drop zone: basically when the drop zone pushes you out, your ship/mech tries to get back and because the "impending doom" is so fast that happens. I will contact anuke about the shooting problem
